### ISSUE TITLE
Is Carrier Code Monospaced?

### ISSUE THREAD

**Issue by addy419** [luciascarlet/CarrierCode#1]
I am a big fan of Courier Prime Code because of it's SF Mono like aesthetic, but it's not a suitable font for terminal emulators. The spacing should be 100 for the font to be categorized as monospaced, do you plan on working on it?

**Comment by luciascarlet** [comment]
Hi, I did set the font as a monospaced font in FontLab and made sure that the width of each character matches, and it does show up in the "Fixed Width" category in Font Book. I tried it out in Terminal and it seems fine to me (screenshot is of Carrier Code in Terminal), but I'm not sure if the spacing is indeed 100. But yeah, it does seem to work for me.

<img width="620" alt="Screenshot 2021-08-01 at 13 52 01" src="https://user-images.githubusercontent.com/13824526/127769843-7181911b-9910-4265-9f2e-eeaf8e5a982d.png">

**Comment by addy419** [comment]
The result of `fc-list : family spacing outline scalable | grep -i Carrier` should be something like `JetBrains Mono:spacing=100:outline=True:scalable=True` but Carrier Code gives `Carrier Code:outline=True:scalable=True`

FontConfig in linux does not think this is a monospaced font.

**Comment by addy419** [comment]
I think the issue is about some character/gylph not conforming to the spacing. Please check https://github.com/be5invis/Sarasa-Gothic/issues/192 for reference.
